### ISSUE TITLE
android_device_qcom_common

### ISSUE THREAD

**Issue by joel16** [Sony-MSM8994-Dev/android_device_sony_kitakami-common#2]
Hey, I was wondering if [this dependency](https://github.com/Sony-MSM8994-Dev/android_device_sony_kitakami-common/blob/lineage-17.1/lineage.dependencies#L7) is still required? LineageOs seems to have discontinued it since 15.1, and it doesn't have a branch for 17.1. Do we still need this or should this be removed?

**Comment by TARKZiM** [comment]
I will remove it, but for now this file is useless.
