### ISSUE TITLE
Z4 Tablet 4g - karin

### ISSUE THREAD

**Issue by mannp** [Sony-MSM8994-Dev/android_device_sony_kitakami-common#7]
Hey, thanks for keeping these Sony devices maintained 👍🏻 

I wondered if your sources work for the Karin device, tree 18.1, perhaps using this device tree?

[android_device_sony_karin](https://github.com/sabarop/android_device_sony_karin)

I am getting build errors and I am not sure if I am correct in trying to use your kitakami-common and msm8994_rework kernel for the karin device?

Thanks for any clarification.

**Comment by TARKZiM** [comment]
Should be fine, they were just copy-pasting my works to there, but i'm not sure what error did you see and i didn't adjust kernel configs for your device so i might not be able to help you.

The repo owner you provided have their cloned repo of mine, you might want to use them instead.

**Comment by mannp** [comment]
I wouldn't want to waste your time with my errors when I am unclear if I am using the correct working sources.

There are a number of trees in the sabarop repo, and it's unclear which ones are current and usable.

On xda your sources are being referenced as the build sources, but frankly so are a number of sources, multiple kernels and so forth, so it is very unclear which ones to actually use.

I will post a similar query on the sabarop repo, thanks.
